version: "2"
services:
  app:
    image: slayerus/deepfacelab:nvidia-1.0
    volumes:
      - ./workspace:/app/workspace
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: bash
