version: "2"
services:
  deepfacelab:
    hostname: deepfacelab
    container_name: deepfacelab
    image: slayerus/deepfacelab:nvidia-1.0
    volumes:
      - "./workspace:/usr/local/deepfacelab/workspace:rw"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    network_mode: "host"
    ipc: host
    environment:
      - DISPLAY=$DISPLAY
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: bash