version: "2"
services:
  deepfacelab:
    image: slayerus/deepfacelab:nvidia-1.0
    volumes:
      - ./workspace:/usr/local/deepfacelab/workspace
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: bash
